#!/usr/bin/env bash
# configures a new Ubuntu machine to respect above requirements
apt-get -y update
apt install -y nginx
echo 'Hello World' > /var/www/html/index.nginx-debian.html 
systemctl restart nginx
