#!/usr/bin/env bash
# install nginx
apt-get -y update
apt-get -y install nginx
chown ubuntu /var/www/html/index.nginx-debian.html 
echo "Hello World" > /var/www/html/index.nginx-debian.html 
service restart nginx
