#!/usr/bin/env bash
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown ubuntu /var/www/html/index.nginx-debian.html 
echo "Hello World" > /var/www/html/index.nginx-debian.html 
sudo service restart nginx
