#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to
# another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html 
sed -i 'server_name; /a location ^/redirect_me/; rewrite {\n https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
