#!/bin/bash
# configures a brand new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html 
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen \[::\]:80 default_server;/a\add_header X-Served-By $(hostname);' /etc/nginx/sites-available/default
sudo service nginx restar
