#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 4316-web-01 52.204.236.97 check
        server 4316-web-02 54.242.115.107:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
