#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with HI at the nineth times
c=1
while ((c <= 10))
do
	if ((c != 9))
	then
		echo "Best School"
	else
		echo "Hi"
	fi
	((c++))
done
