#!/usr/bin/env bash
# This script is displaying number to 1 to 20 with some sentences at some conditions
num=1
while ((num <= 20))
do
	echo $num
	case $num in
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
	esac
	((num++))
done
