#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hour=0
min=1
while ((hour <= 12))
do
	echo "Hour: $hour"
	((hour++))
	while ((min <= 59))
	do
		echo "$min"
	((min++))
	done
	min=1
done
